sonar.projectKey=HydroSense-Integra_server-app-ui_052eceda-f7d6-4381-8909-b68e11c0a728
sonar.organization=HydroSense-Integra
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.js, **/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://radicalrack.synology.me:9000/
sonar.login=sqa_4e940054e53b086fbe7c220bd83d6099979512ae

# ESLint Report Path
sonar.eslint.reportPaths=eslint-report.json